### ISSUE TITLE
Update failed with incorrect files

### ISSUE THREAD

**Issue by gamebits** [aschweigert/newspack-plugin-update-checker#4]
On 26 Nov 2023, an attempted update to [Newspack Plugin v2.11.1](https://github.com/Automattic/newspack-plugin/releases/tag/v2.11.1) (released 20 Nov 2023) failed, with the version installed on my site being replaced with the contents of the Newspack Plugin repo instead of the built release. The ensuing fatal error brought the site down.

Here is the `debug.log`:
```
Fatal error: Uncaught Error: Failed opening required 'vendor/autoload.php' (include_path='.:') in /home/dh_k455ht/a2central.com/wp-content/plugins/newspack-plugin/newspack.php:27 Stack trace: #0 /home/dh_k455ht/a2central.com/wp-settings.php(473): include_once() #1 /home/dh_k455ht/a2central.com/wp-config.php(107): require_once('/home/dh_k455ht...') #2 /home/dh_k455ht/a2central.com/wp-load.php(50): require_once('/home/dh_k455ht...') #3 /home/dh_k455ht/a2central.com/wp-admin/admin.php(34): require_once('/home/dh_k455ht...') #4 /home/dh_k455ht/a2central.com/wp-admin/index.php(10): require_once('/home/dh_k455ht...') #5 {main} thrown in /home/dh_k455ht/a2central.com/wp-content/plugins/newspack-plugin/newspack.php on line 27
```

The referenced `vendors` folder was missing. I SFTPed into the site and found the plugin folder contained many files not included in `newspack-plugin.zip`, all of them timestamped an hour earlier:

![newspack-plugin-transmit](https://github.com/aschweigert/newspack-plugin-update-checker/assets/12199101/f6b82a8c-3de5-47d7-81f3-92b293869a73)

I deleted the folder and uploaded a fresh copy of the plugin, bringing the site back online.

**Comment by aschweigert** [comment]
Hm, I haven't run into this particular bug yet so maybe it was just an issue with that release? Let me know if it happens again and maybe we can try to hunt down what's causing it.
